import type { Oas } from "@mihari/oas";

import {
  kebabCase,
  listOperations,
  openApiPathToStubbed,
  specTitle,
  type GenerateResult,
  type NormalisedOperation,
} from "./shared.ts";

export interface GenerateJestOptions {
  packageName?: string;
}

/**
 * Generates a Jest blackbox test suite. Each operation gets one test file that
 * hits the running server via fetch with stubbed required parameters.
 */
export function generateJest(oas: Oas, options: GenerateJestOptions = {}): GenerateResult {
  const title = specTitle(oas);
  const packageName = options.packageName ?? `${kebabCase(title)}-tests-jest`;
  const operations = listOperations(oas);

  return {
    files: [
      { path: "package.json", content: renderPackageJson(packageName) },
      { path: "jest.config.ts", content: renderJestConfig() },
      { path: "tsconfig.json", content: renderTsconfig() },
      { path: ".env.example", content: renderEnvExample() },
      { path: "README.md", content: renderReadme(title, operations.length) },
      { path: "tests/helpers/validator.ts", content: renderValidator() },
      ...operations.map((op) => ({
        path: `schemas/${op.safeId}.response.json`,
        content: `${JSON.stringify(op.successResponse?.schema ?? true, null, 2)}\n`,
      })),
      ...operations.map((op) => ({
        path: `tests/${op.safeId}.test.ts`,
        content: renderTest(op),
      })),
    ],
  };
}

function renderValidator(): string {
  return `import Ajv from "ajv";
import addFormats from "ajv-formats";

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

/**
 * Returns a validation helper for the given JSON schema. Passes through when
 * the schema is \`true\` (operation did not declare a response shape).
 */
export function makeValidator(schema: unknown) {
  if (schema === true || schema === undefined || schema === null) {
    return () => ({ valid: true as const, errors: null });
  }
  const validate = ajv.compile(schema as object);
  return (body: unknown) => {
    const valid = validate(body);
    return valid
      ? ({ valid: true as const, errors: null })
      : ({ valid: false as const, errors: validate.errors ?? [] });
  };
}
`;
}

function renderPackageJson(name: string): string {
  return (
    JSON.stringify(
      {
        name,
        version: "0.1.0",
        private: true,
        type: "module",
        scripts: {
          test: "jest",
        },
        devDependencies: {
          "@types/jest": "^29.5.12",
          ajv: "^8.17.1",
          "ajv-formats": "^3.0.1",
          jest: "^29.7.0",
          "ts-jest": "^29.1.0",
          typescript: "^5.7.0",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function renderJestConfig(): string {
  return `import type { Config } from "jest";

const config: Config = {
  preset: "ts-jest",
  testEnvironment: "node",
  testMatch: ["<rootDir>/tests/**/*.test.ts"],
  testTimeout: 10_000,
};

export default config;
`;
}

function renderTsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "node",
          strict: true,
          esModuleInterop: true,
          resolveJsonModule: true,
          skipLibCheck: true,
          types: ["jest", "node"],
        },
        include: ["tests", "jest.config.ts"],
      },
      null,
      2,
    ) + "\n"
  );
}

function renderEnvExample(): string {
  return `# Base URL of the target API\nAPI_BASE_URL=http://localhost:3000\n\n# Optional bearer token\nAPI_TOKEN=\n`;
}

function renderReadme(title: string, count: number): string {
  return `# ${title} blackbox tests (Jest)\n\nGenerated by \`mihari api generate tests --framework jest\`. ${count} operation${count === 1 ? "" : "s"} covered.\n\n## Run\n\n\`\`\`sh\ncp .env.example .env\n# start the API server, then:\nnpm install\nnpm test\n\`\`\`\n\nEach test hits the running server via \`fetch\`, stubs any required path/query/body fields and asserts a 2xx response. Tighten the assertions as needed.\n`;
}

function renderTest(op: NormalisedOperation): string {
  const stubs: Record<string, string> = {};
  for (const p of op.pathParams) stubs[p.name] = `stub-${p.name}`;
  const filledPath = openApiPathToStubbed(op.path, stubs);
  const requiredQuery = op.queryParams.filter((p) => p.required);
  const querySuffix = requiredQuery.length
    ? `?${requiredQuery.map((p) => `${encodeURIComponent(p.name)}=stub`).join("&")}`
    : "";

  const hasBody = !!op.requestBodySchema;
  const bodyLine = hasBody ? `  body: JSON.stringify({}),\n` : "";
  const contentTypeLine = hasBody ? `    "Content-Type": ${JSON.stringify(op.requestBodyContentType ?? "application/json")},\n` : "";

  const methodUpper = op.method.toUpperCase();
  return `import { makeValidator } from "./helpers/validator";
import responseSchema from "../schemas/${op.safeId}.response.json";

const baseUrl = process.env.API_BASE_URL ?? "http://localhost:3000";
const token = process.env.API_TOKEN;
const validate = makeValidator(responseSchema);

describe("${methodUpper} ${op.path} (${op.operationId})", () => {
  it("returns a 2xx response matching the declared schema", async () => {
    const url = new URL("${filledPath}${querySuffix}", baseUrl);
    const response = await fetch(url.toString(), {
      method: ${JSON.stringify(methodUpper)},
      headers: {
${contentTypeLine}        Accept: "application/json",
        ...(token ? { Authorization: \`Bearer \${token}\` } : {}),
      },
${bodyLine}    });

    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);

    const contentType = response.headers.get("content-type") ?? "";
    if (contentType.includes("application/json") && response.status !== 204) {
      const body = await response.json();
      const result = validate(body);
      if (!result.valid) {
        throw new Error(
          "Response body does not match declared schema:\\n" +
            JSON.stringify(result.errors, null, 2),
        );
      }
    }
  });
});
`;
}
