import type { Oas } from "@mihari/oas";

import {
  kebabCase,
  listOperations,
  openApiPathToStubbed,
  specTitle,
  type GenerateResult,
  type NormalisedOperation,
} from "./shared.ts";

export interface GeneratePlaywrightOptions {
  packageName?: string;
}

/**
 * Generates a Playwright blackbox test suite built on the `request` fixture
 * (no browser). One spec file, one `test()` per operation.
 */
export function generatePlaywright(
  oas: Oas,
  options: GeneratePlaywrightOptions = {},
): GenerateResult {
  const title = specTitle(oas);
  const packageName = options.packageName ?? `${kebabCase(title)}-tests-playwright`;
  const operations = listOperations(oas);

  return {
    files: [
      { path: "package.json", content: renderPackageJson(packageName) },
      { path: "playwright.config.ts", content: renderConfig() },
      { path: "tsconfig.json", content: renderTsconfig() },
      { path: ".env.example", content: renderEnvExample() },
      { path: "README.md", content: renderReadme(title, operations.length) },
      { path: "tests/helpers/validator.ts", content: renderValidator() },
      ...operations.map((op) => ({
        path: `schemas/${op.safeId}.response.json`,
        content: `${JSON.stringify(op.successResponse?.schema ?? true, null, 2)}\n`,
      })),
      { path: "tests/api.spec.ts", content: renderSpec(operations) },
    ],
  };
}

function renderValidator(): string {
  return `import Ajv from "ajv";
import addFormats from "ajv-formats";

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

export function makeValidator(schema: unknown) {
  if (schema === true || schema === undefined || schema === null) {
    return () => ({ valid: true as const, errors: null });
  }
  const validate = ajv.compile(schema as object);
  return (body: unknown) => {
    const valid = validate(body);
    return valid
      ? ({ valid: true as const, errors: null })
      : ({ valid: false as const, errors: validate.errors ?? [] });
  };
}
`;
}

function renderPackageJson(name: string): string {
  return (
    JSON.stringify(
      {
        name,
        version: "0.1.0",
        private: true,
        type: "module",
        scripts: {
          test: "playwright test",
          "install-browsers": "playwright install",
        },
        devDependencies: {
          "@playwright/test": "^1.48.0",
          ajv: "^8.17.1",
          "ajv-formats": "^3.0.1",
          typescript: "^5.7.0",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function renderConfig(): string {
  return `import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  timeout: 30_000,
  reporter: "list",
  use: {
    baseURL: process.env.API_BASE_URL ?? "http://localhost:3000",
    extraHTTPHeaders: process.env.API_TOKEN
      ? { Authorization: \`Bearer \${process.env.API_TOKEN}\` }
      : {},
  },
});
`;
}

function renderTsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          resolveJsonModule: true,
          skipLibCheck: true,
          types: ["node"],
        },
        include: ["tests", "playwright.config.ts"],
      },
      null,
      2,
    ) + "\n"
  );
}

function renderEnvExample(): string {
  return `API_BASE_URL=http://localhost:3000\nAPI_TOKEN=\n`;
}

function renderReadme(title: string, count: number): string {
  return `# ${title} blackbox tests (Playwright)\n\nGenerated by \`mihari api generate tests --framework playwright\`. ${count} operation${count === 1 ? "" : "s"} covered using Playwright's \`request\` fixture — no browser required.\n\n## Run\n\n\`\`\`sh\ncp .env.example .env\nnpm install\nnpx playwright test\n\`\`\`\n`;
}

function renderSpec(operations: NormalisedOperation[]): string {
  const imports = operations
    .map(
      (op) =>
        `import ${op.safeId}Schema from "../schemas/${op.safeId}.response.json";`,
    )
    .join("\n");
  const blocks = operations.map((op) => renderTest(op)).join("\n\n");
  return `import { test, expect } from "@playwright/test";\nimport { makeValidator } from "./helpers/validator";\n${imports}\n\ntest.describe("API blackbox", () => {\n${blocks}\n});\n`;
}

function renderTest(op: NormalisedOperation): string {
  const stubs: Record<string, string> = {};
  for (const p of op.pathParams) stubs[p.name] = `stub-${p.name}`;
  const filledPath = openApiPathToStubbed(op.path, stubs);
  const requiredQuery = op.queryParams.filter((p) => p.required);
  const querySuffix = requiredQuery.length
    ? `?${requiredQuery.map((p) => `${encodeURIComponent(p.name)}=stub`).join("&")}`
    : "";

  const method = op.method.toLowerCase();
  const methodUpper = op.method.toUpperCase();
  const bodyOption = op.requestBodySchema ? `, { data: {} }` : "";

  return `  test("${methodUpper} ${op.path} (${op.operationId})", async ({ request }) => {
    const response = await request.${method}("${filledPath}${querySuffix}"${bodyOption});
    expect(response.ok()).toBeTruthy();
    const contentType = response.headers()["content-type"] ?? "";
    if (contentType.includes("application/json") && response.status() !== 204) {
      const body = await response.json();
      const validate = makeValidator(${op.safeId}Schema);
      const result = validate(body);
      if (!result.valid) {
        throw new Error(
          "Response does not match declared schema: " +
            JSON.stringify(result.errors, null, 2),
        );
      }
    }
  });`;
}
