import type { Oas } from "@mihari/oas";

import {
  camelCase,
  clientClassNameFromTitle,
  iterSchemas,
  kebabCase,
  listOperations,
  pascalCase,
  schemaIsArrayOfRef,
  schemaIsRef,
  schemaToJava,
  specTitle,
  type GenerateResult,
  type NormalisedOperation,
} from "./shared.ts";

export interface GenerateSdkJavaOptions {
  /** Maven groupId. Default: `com.example`. */
  groupId?: string;
  /** Maven artifactId. Default: kebab-case title + `-sdk`. */
  artifactId?: string;
  /** Java class name. Default: `<Title>Client`. */
  className?: string;
  /** Emit methods that return `CompletableFuture<T>` via `sendAsync`. */
  async?: boolean;
}

/**
 * Generates a Maven-based Java SDK using the stdlib HttpClient (JDK 11+) and
 * Jackson for JSON. Methods return `Object` (Jackson's deserialised tree) and
 * throw the usual checked exceptions (`IOException`, `InterruptedException`).
 */
export function generateSdkJava(
  oas: Oas,
  options: GenerateSdkJavaOptions = {},
): GenerateResult {
  const title = specTitle(oas);
  const groupId = options.groupId ?? "com.example";
  const artifactId = options.artifactId ?? `${kebabCase(title)}-sdk`;
  const className = options.className ?? clientClassNameFromTitle(title);
  const packageName = `${groupId}.${pascalCase(title).toLowerCase()}`;
  const packagePath = packageName.replace(/\./g, "/");
  const operations = listOperations(oas);
  const schemas = iterSchemas(oas);
  const isAsync = options.async === true;

  return {
    files: [
      { path: "pom.xml", content: renderPom(groupId, artifactId) },
      { path: ".gitignore", content: "target/\n*.iml\n.idea/\n" },
      {
        path: "README.md",
        content: renderReadme(title, groupId, artifactId, className, packageName, isAsync),
      },
      {
        path: `src/main/java/${packagePath}/${className}.java`,
        content: renderClient(packageName, className, operations, isAsync),
      },
      {
        path: `src/main/java/${packagePath}/ApiException.java`,
        content: renderApiException(packageName),
      },
      ...schemas.map(({ name, schema }) => ({
        path: `src/main/java/${packagePath}/${name}.java`,
        content: renderDto(packageName, name, schema),
      })),
    ],
  };
}

function renderDto(packageName: string, name: string, schema: unknown): string {
  if (!schema || typeof schema !== "object") {
    return `package ${packageName};\n\npublic class ${name} {}\n`;
  }
  const s = schema as Record<string, unknown>;
  if (s.type !== "object" || !s.properties) {
    return `package ${packageName};\n\n// TODO: ${name} is not an object — edit this alias manually if needed.\npublic class ${name} {}\n`;
  }
  const properties = s.properties as Record<string, unknown>;
  const fields: string[] = [];
  for (const [key, propSchema] of Object.entries(properties)) {
    const fieldType = schemaToJava(propSchema);
    const fieldName = camelCase(key).replace(/[^a-zA-Z0-9_]/g, "");
    const rename = fieldName === key ? "" : `    @com.fasterxml.jackson.annotation.JsonProperty("${key}")\n`;
    fields.push(`${rename}    public ${fieldType} ${fieldName};`);
  }
  return `package ${packageName};

/** Auto-generated DTO. Do not edit by hand. */
public class ${name} {
${fields.join("\n")}
}
`;
}

function renderPom(groupId: string, artifactId: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
           http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>${groupId}</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.17.0</version>
    </dependency>
  </dependencies>
</project>
`;
}

function renderReadme(
  title: string,
  groupId: string,
  artifactId: string,
  className: string,
  packageName: string,
  isAsync: boolean,
): string {
  const flag = isAsync ? " --async" : "";
  const mode = isAsync ? "asynchronous (`CompletableFuture<T>`)" : "synchronous";
  const usage = isAsync
    ? `client.listPets(10)
  .thenAccept(pets -> System.out.println(pets))
  .join();`
    : `var pets = client.listPets(10);`;
  return `# ${title} SDK (Java)

Generated by \`mihari api generate sdk --lang java${flag}\`. ${mode} client on top of stdlib \`java.net.http.HttpClient\` (JDK 11+) + Jackson.

## Install

\`\`\`sh
mvn install
\`\`\`

## Usage

\`\`\`java
import ${packageName}.${className};

var client = new ${className}("https://api.example.com", "token");
${usage}
\`\`\`

Or resolve the base URL from the spec:

\`\`\`java
var client = ${className}.fromSpec("https://api.example.com/openapi.json", "token");
\`\`\`

Maven coordinates: \`${groupId}:${artifactId}:0.1.0\`.
`;
}

function renderApiException(packageName: string): string {
  return `package ${packageName};

/** Thrown for non-2xx HTTP responses. */
public class ApiException extends RuntimeException {
    public final int status;
    public final String body;

    public ApiException(int status, String body) {
        super("HTTP " + status + ": " + body);
        this.status = status;
        this.body = body;
    }
}
`;
}

function renderClient(
  packageName: string,
  className: string,
  operations: NormalisedOperation[],
  isAsync: boolean,
): string {
  const methods = operations.map((op) => renderMethod(op, isAsync)).join("\n\n");
  return `package ${packageName};

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;

/** Auto-generated client. Do not edit by hand. */
public class ${className} {
    private final String baseUrl;
    private final String token;
    private final HttpClient http;
    private final ObjectMapper mapper = new ObjectMapper();

    public ${className}(String baseUrl, String token) {
        this.baseUrl = baseUrl.endsWith("/") ? baseUrl.substring(0, baseUrl.length() - 1) : baseUrl;
        this.token = token;
        this.http = HttpClient.newHttpClient();
    }

    /** Build a client by reading \`servers[0].url\` from the JSON spec at {@code specUrl}. */
    public static ${className} fromSpec(String specUrl, String token) throws IOException, InterruptedException {
        HttpClient bootstrap = HttpClient.newHttpClient();
        HttpResponse<String> resp = bootstrap.send(
            HttpRequest.newBuilder(URI.create(specUrl)).GET().build(),
            HttpResponse.BodyHandlers.ofString()
        );
        if (resp.statusCode() / 100 != 2) {
            throw new ApiException(resp.statusCode(), resp.body());
        }
        ObjectMapper om = new ObjectMapper();
        var node = om.readTree(resp.body());
        var servers = node.get("servers");
        if (servers == null || !servers.isArray() || servers.size() == 0) {
            throw new IllegalArgumentException("OpenAPI spec has no servers[]");
        }
        String url = servers.get(0).get("url").asText();
        return new ${className}(url, token);
    }

    private HttpRequest.Builder baseRequest(String url) {
        HttpRequest.Builder b = HttpRequest.newBuilder(URI.create(url))
            .header("Accept", "application/json");
        if (token != null) {
            b = b.header("Authorization", "Bearer " + token);
        }
        return b;
    }

    private static String enc(Object value) {
        return URLEncoder.encode(String.valueOf(value), StandardCharsets.UTF_8);
    }

    private <T> T send(HttpRequest request, Class<T> type) throws IOException, InterruptedException {
        HttpResponse<String> resp = http.send(request, HttpResponse.BodyHandlers.ofString());
        if (resp.statusCode() / 100 != 2) {
            throw new ApiException(resp.statusCode(), resp.body());
        }
        if (resp.body() == null || resp.body().isEmpty()) {
            return null;
        }
        String ct = resp.headers().firstValue("content-type").orElse("");
        if (!ct.contains("application/json")) {
            return null;
        }
        return mapper.readValue(resp.body(), type);
    }

    private <T> T send(HttpRequest request, com.fasterxml.jackson.core.type.TypeReference<T> typeRef)
            throws IOException, InterruptedException {
        HttpResponse<String> resp = http.send(request, HttpResponse.BodyHandlers.ofString());
        if (resp.statusCode() / 100 != 2) {
            throw new ApiException(resp.statusCode(), resp.body());
        }
        if (resp.body() == null || resp.body().isEmpty()) {
            return null;
        }
        String ct = resp.headers().firstValue("content-type").orElse("");
        if (!ct.contains("application/json")) {
            return null;
        }
        return mapper.readValue(resp.body(), typeRef);
    }

    private <T> java.util.concurrent.CompletableFuture<T> sendAsync(HttpRequest request, Class<T> type) {
        return http.sendAsync(request, HttpResponse.BodyHandlers.ofString())
            .thenApply(resp -> decodeResponse(resp, body -> mapper.readValue(body, type)));
    }

    private <T> java.util.concurrent.CompletableFuture<T> sendAsync(HttpRequest request, com.fasterxml.jackson.core.type.TypeReference<T> typeRef) {
        return http.sendAsync(request, HttpResponse.BodyHandlers.ofString())
            .thenApply(resp -> decodeResponse(resp, body -> mapper.readValue(body, typeRef)));
    }

    @FunctionalInterface
    private interface Deserialiser<T> {
        T apply(String body) throws java.io.IOException;
    }

    private <T> T decodeResponse(HttpResponse<String> resp, Deserialiser<T> deserialiser) {
        if (resp.statusCode() / 100 != 2) {
            throw new java.util.concurrent.CompletionException(
                new ApiException(resp.statusCode(), resp.body())
            );
        }
        if (resp.body() == null || resp.body().isEmpty()) {
            return null;
        }
        String ct = resp.headers().firstValue("content-type").orElse("");
        if (!ct.contains("application/json")) {
            return null;
        }
        try {
            return deserialiser.apply(resp.body());
        } catch (java.io.IOException e) {
            throw new java.util.concurrent.CompletionException(e);
        }
    }

${methods}
}
`;
}

function renderMethod(op: NormalisedOperation, isAsync: boolean): string {
  const name = javaMethodName(op.operationId);
  const pathArgs: string[] = [];
  const pathBuilderLines: string[] = [];

  for (const p of op.pathParams) {
    const ident = camelCase(p.name);
    const javaType = javaTypeForSchema(p.schema);
    pathArgs.push(`${javaType} ${ident}`);
    pathBuilderLines.push(
      `        path = path.replace("{${p.name}}", enc(${ident}));`,
    );
  }

  const queryArgs: string[] = [];
  const queryBuildLines: string[] = [];
  for (const p of op.queryParams) {
    const ident = camelCase(p.name);
    const javaType = p.required
      ? javaTypeForSchema(p.schema)
      : javaBoxedType(p.schema);
    queryArgs.push(`${javaType} ${ident}`);
    if (p.required) {
      queryBuildLines.push(
        `        query.append(query.length() == 0 ? "?" : "&").append(${JSON.stringify(p.name)}).append("=").append(enc(${ident}));`,
      );
    } else {
      queryBuildLines.push(
        `        if (${ident} != null) query.append(query.length() == 0 ? "?" : "&").append(${JSON.stringify(p.name)}).append("=").append(enc(${ident}));`,
      );
    }
  }

  const bodyType = javaBodyType(op);
  const args = [...pathArgs, ...queryArgs];
  if (op.requestBodySchema) args.push(`${bodyType} body`);

  const { returnType, sendCall } = javaReturn(op);

  const bodyLine = op.requestBodySchema
    ? `        String json = mapper.writeValueAsString(body);
        HttpRequest request = baseRequest(url)
            .header("Content-Type", "application/json")
            .method(${JSON.stringify(op.method.toUpperCase())}, HttpRequest.BodyPublishers.ofString(json))
            .build();`
    : `        HttpRequest request = baseRequest(url)
            .method(${JSON.stringify(op.method.toUpperCase())}, HttpRequest.BodyPublishers.noBody())
            .build();`;

  const doc = op.summary
    ? `    /** ${op.summary} — ${op.method.toUpperCase()} ${op.path} */`
    : `    /** ${op.method.toUpperCase()} ${op.path} */`;

  const declaredReturn = isAsync
    ? `java.util.concurrent.CompletableFuture<${returnType}>`
    : returnType;
  const throwsClause = isAsync ? "" : " throws java.io.IOException, InterruptedException";
  const bodyLineForAsync = op.requestBodySchema
    ? `        String json;
        try {
            json = mapper.writeValueAsString(body);
        } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
            java.util.concurrent.CompletableFuture<${returnType}> failed = new java.util.concurrent.CompletableFuture<>();
            failed.completeExceptionally(e);
            return failed;
        }
        HttpRequest request = baseRequest(url)
            .header("Content-Type", "application/json")
            .method(${JSON.stringify(op.method.toUpperCase())}, HttpRequest.BodyPublishers.ofString(json))
            .build();`
    : `        HttpRequest request = baseRequest(url)
            .method(${JSON.stringify(op.method.toUpperCase())}, HttpRequest.BodyPublishers.noBody())
            .build();`;

  if (isAsync) {
    const asyncSend = buildAsyncSendCall(op, returnType);
    return `${doc}
    public ${declaredReturn} ${name}(${args.join(", ")})${throwsClause} {
        String path = ${JSON.stringify(op.path)};
${pathBuilderLines.join("\n") || "        // no path params"}
        StringBuilder query = new StringBuilder();
${queryBuildLines.join("\n") || "        // no query params"}
        String url = baseUrl + path + query.toString();
${bodyLineForAsync}
        return ${asyncSend};
    }`;
  }

  return `${doc}
    public ${declaredReturn} ${name}(${args.join(", ")})${throwsClause} {
        String path = ${JSON.stringify(op.path)};
${pathBuilderLines.join("\n") || "        // no path params"}
        StringBuilder query = new StringBuilder();
${queryBuildLines.join("\n") || "        // no query params"}
        String url = baseUrl + path + query.toString();
${bodyLine}
        return ${sendCall};
    }`;
}

function buildAsyncSendCall(op: NormalisedOperation, _returnType: string): string {
  const schema = op.successResponse?.schema;
  const refName = schema ? schemaIsRef(schema) : null;
  const arrayRef = schema ? schemaIsArrayOfRef(schema) : null;
  if (refName) {
    return `sendAsync(request, ${refName}.class)`;
  }
  if (arrayRef) {
    return `sendAsync(request, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<${arrayRef}>>() {})`;
  }
  return `sendAsync(request, Object.class)`;
}

function javaReturn(op: NormalisedOperation): { returnType: string; sendCall: string } {
  const schema = op.successResponse?.schema;
  if (!schema) return { returnType: "Object", sendCall: "send(request, Object.class)" };
  const refName = schemaIsRef(schema);
  if (refName) {
    return { returnType: refName, sendCall: `send(request, ${refName}.class)` };
  }
  const arrayRef = schemaIsArrayOfRef(schema);
  if (arrayRef) {
    return {
      returnType: `java.util.List<${arrayRef}>`,
      sendCall: `send(request, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<${arrayRef}>>() {})`,
    };
  }
  return { returnType: "Object", sendCall: "send(request, Object.class)" };
}

function javaBodyType(op: NormalisedOperation): string {
  const schema = op.requestBodySchema;
  if (!schema) return "Object";
  const refName = schemaIsRef(schema);
  if (refName) return refName;
  const arrayRef = schemaIsArrayOfRef(schema);
  if (arrayRef) return `java.util.List<${arrayRef}>`;
  return "Object";
}

function javaMethodName(operationId: string): string {
  return camelCase(operationId).replace(/[^a-zA-Z0-9_]/g, "");
}

function javaTypeForSchema(schema: unknown): string {
  if (!schema || typeof schema !== "object") return "Object";
  const s = schema as Record<string, unknown>;
  if (Array.isArray(s.enum)) return "String";
  switch (s.type) {
    case "string":
      return "String";
    case "integer":
      return "int";
    case "number":
      return "double";
    case "boolean":
      return "boolean";
    case "array":
      return "java.util.List<Object>";
    default:
      return "Object";
  }
}

function javaBoxedType(schema: unknown): string {
  const raw = javaTypeForSchema(schema);
  switch (raw) {
    case "int":
      return "Integer";
    case "double":
      return "Double";
    case "boolean":
      return "Boolean";
    default:
      return raw;
  }
}
