import type { Oas } from "@mihari/oas";

import {
  clientClassNameFromTitle,
  kebabCase,
  listOperations,
  pythonSafeIdentifier,
  snakeCase,
  specTitle,
  type GenerateResult,
  type NormalisedOperation,
} from "./shared.ts";

export interface GenerateSdkPythonOptions {
  packageName?: string;
  className?: string;
}

/**
 * Generates a minimal Python SDK that wraps the spec's operations using the
 * `requests` library. Naming follows Python conventions (snake_case methods,
 * PEP 8 module names) while the class name mirrors the TypeScript SDK so the
 * two feel like siblings.
 */
export function generateSdkPython(
  oas: Oas,
  options: GenerateSdkPythonOptions = {},
): GenerateResult {
  const title = specTitle(oas);
  const packageName = options.packageName ?? `${kebabCase(title)}-sdk`;
  const moduleName = snakeCase(packageName).replace(/-/g, "_");
  const className = options.className ?? clientClassNameFromTitle(title);
  const operations = listOperations(oas);

  return {
    files: [
      { path: "pyproject.toml", content: renderPyproject(packageName, moduleName) },
      { path: "README.md", content: renderReadme(title, moduleName, className) },
      { path: ".gitignore", content: "dist/\nbuild/\n*.egg-info/\n__pycache__/\n.venv/\n" },
      { path: `${moduleName}/__init__.py`, content: renderInit(className) },
      { path: `${moduleName}/client.py`, content: renderClient(className, operations) },
    ],
  };
}

function renderPyproject(packageName: string, moduleName: string): string {
  return `[project]
name = "${packageName}"
version = "0.1.0"
description = "Generated Python SDK"
requires-python = ">=3.9"
dependencies = [
  "requests>=2.31,<3",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["${moduleName}*"]
`;
}

function renderInit(className: string): string {
  return `from .client import ${className}\n\n__all__ = ["${className}"]\n`;
}

function renderReadme(title: string, moduleName: string, className: string): string {
  return `# ${title} SDK (Python)

Generated by \`mihari api generate sdk --lang python\`. One method per operation.

## Install (editable)

\`\`\`sh
python -m venv .venv && source .venv/bin/activate
pip install -e .
\`\`\`

## Usage

\`\`\`py
from ${moduleName} import ${className}

client = ${className}(base_url="https://api.example.com", token="...")
pets = client.list_pets(limit=10)
\`\`\`

Method names are snake_case derived from the operation's \`operationId\`. All
methods raise \`requests.HTTPError\` on non-2xx responses.
`;
}

function renderClient(className: string, operations: NormalisedOperation[]): string {
  const methods = operations.map((op) => renderMethod(op)).join("\n");
  return `"""Auto-generated HTTP client. Do not edit by hand."""
from __future__ import annotations

from typing import Any, Optional
import requests


class ${className}:
    def __init__(
        self,
        base_url: str,
        token: Optional[str] = None,
        session: Optional[requests.Session] = None,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.token = token
        self._session = session or requests.Session()

    @classmethod
    def from_spec(
        cls,
        spec_url: str,
        token: Optional[str] = None,
        session: Optional[requests.Session] = None,
    ) -> "${className}":
        """Build a client by reading baseUrl from the first \`servers[]\` of
        the JSON OpenAPI document at \`spec_url\`."""
        s = session or requests.Session()
        response = s.get(spec_url, timeout=10)
        response.raise_for_status()
        spec = response.json()
        servers = spec.get("servers") or []
        if not servers or not servers[0].get("url"):
            raise RuntimeError(f"OpenAPI spec at {spec_url} has no servers[]")
        return cls(base_url=servers[0]["url"], token=token, session=s)

    def _headers(self, extra: Optional[dict] = None) -> dict:
        h: dict = {"Accept": "application/json"}
        if self.token:
            h["Authorization"] = f"Bearer {self.token}"
        if extra:
            h.update(extra)
        return h

${methods}`;
}

function renderMethod(op: NormalisedOperation): string {
  const name = pythonSafeIdentifier(op.operationId);
  const pathArgs: string[] = [];
  const pathSubstitutions: string[] = [];

  for (const p of op.pathParams) {
    const ident = pythonSafeIdentifier(p.name);
    const pyType = pythonTypeForSchema(p.schema);
    pathArgs.push(`${ident}: ${pyType}`);
    pathSubstitutions.push(
      `.replace("{${p.name}}", requests.utils.quote(str(${ident}), safe=""))`,
    );
  }

  const keywordArgs: string[] = [];
  const queryAssignments: string[] = [];
  for (const p of op.queryParams) {
    const ident = pythonSafeIdentifier(p.name);
    const pyType = pythonTypeForSchema(p.schema);
    if (p.required) {
      keywordArgs.push(`${ident}: ${pyType}`);
      queryAssignments.push(`        params[${JSON.stringify(p.name)}] = ${ident}`);
    } else {
      keywordArgs.push(`${ident}: Optional[${pyType}] = None`);
      queryAssignments.push(
        `        if ${ident} is not None:\n            params[${JSON.stringify(p.name)}] = ${ident}`,
      );
    }
  }

  const hasBody = !!op.requestBodySchema;
  if (hasBody) {
    const bodyType = pythonTypeForSchema(op.requestBodySchema);
    if (op.requestBodyRequired) {
      keywordArgs.push(`body: ${bodyType}`);
    } else {
      keywordArgs.push(`body: Optional[${bodyType}] = None`);
    }
  }

  keywordArgs.push(`headers: Optional[dict] = None`);

  const args = [
    "self",
    ...pathArgs,
    ...(keywordArgs.length ? ["*", ...keywordArgs] : []),
  ].join(", ");

  const pathExpr =
    pathSubstitutions.length === 0
      ? JSON.stringify(op.path)
      : `${JSON.stringify(op.path)}${pathSubstitutions.join("")}`;

  const bodyLine = hasBody ? "\n            json=body," : "";
  const paramsBlock = op.queryParams.length
    ? `        params: dict = {}\n${queryAssignments.join("\n")}`
    : "        params: dict = {}";

  const docLines: string[] = [];
  if (op.summary) docLines.push(op.summary);
  docLines.push(`${op.method.toUpperCase()} ${op.path}`);
  const doc = docLines.length
    ? `        """${docLines.join(" — ")}"""\n`
    : "";

  return `    def ${name}(${args}) -> Any:
${doc}${paramsBlock}
        url = self.base_url + ${pathExpr}
        response = self._session.request(
            ${JSON.stringify(op.method.toUpperCase())},
            url,
            params=params or None,
            headers=self._headers(headers),${bodyLine}
            timeout=30,
        )
        response.raise_for_status()
        if response.content and "application/json" in response.headers.get("Content-Type", ""):
            return response.json()
        return response.content
`;
}

function pythonTypeForSchema(schema: unknown): string {
  if (!schema || typeof schema !== "object") return "Any";
  const s = schema as Record<string, unknown>;
  if (Array.isArray(s.enum)) return "str";
  switch (s.type) {
    case "string":
      return "str";
    case "integer":
      return "int";
    case "number":
      return "float";
    case "boolean":
      return "bool";
    case "array":
      return "list";
    case "object":
      return "dict";
    default:
      return "Any";
  }
}
