import type { Oas } from "@mihari/oas";

import {
  goExportedIdentifier,
  kebabCase,
  listOperations,
  snakeCase,
  specTitle,
  type GenerateResult,
  type NormalisedOperation,
} from "./shared.ts";

export interface GenerateSdkGoOptions {
  /** Module path written to go.mod. Default: `example.com/<kebab-title>-sdk`. */
  modulePath?: string;
  /** Go package name. Default: derived from title (lowercase, no dashes). */
  packageName?: string;
}

/**
 * Generates a single-file Go SDK built on stdlib `net/http`. Zero third-party
 * dependencies. Exported symbols follow Go conventions (PascalCase, doc
 * comments starting with the identifier).
 */
export function generateSdkGo(
  oas: Oas,
  options: GenerateSdkGoOptions = {},
): GenerateResult {
  const title = specTitle(oas);
  const modulePath = options.modulePath ?? `example.com/${kebabCase(title)}-sdk`;
  const packageName = options.packageName ?? sanitizeGoPackageName(title);
  const operations = listOperations(oas);

  return {
    files: [
      { path: "go.mod", content: `module ${modulePath}\n\ngo 1.21\n` },
      { path: "README.md", content: renderReadme(title, modulePath, packageName) },
      { path: "client.go", content: renderClient(packageName, operations) },
    ],
  };
}

function sanitizeGoPackageName(title: string): string {
  const snake = snakeCase(title).replace(/[^a-zA-Z0-9]/g, "");
  const pkg = snake || "sdk";
  return pkg.startsWith("_") || /^[0-9]/.test(pkg) ? `sdk${pkg}` : pkg;
}

function renderReadme(title: string, modulePath: string, packageName: string): string {
  return `# ${title} SDK (Go)

Generated by \`mihari api generate sdk --lang go\`. Uses stdlib \`net/http\` only.

## Install

\`\`\`sh
go get ${modulePath}
\`\`\`

## Usage

\`\`\`go
package main

import (
  "fmt"
  "${modulePath}"
)

func main() {
  client := ${packageName}.NewClient("https://api.example.com", "token")
  pets, err := client.ListPets(nil)
  if err != nil {
    panic(err)
  }
  fmt.Println(pets)
}
\`\`\`

All methods return \`(any, error)\`. A non-2xx response is surfaced as an
\`*APIError\` carrying the status code and body.
`;
}

function renderClient(packageName: string, operations: NormalisedOperation[]): string {
  const methods = operations.map((op) => renderMethod(op)).join("\n\n");
  return `// Code generated by mihari. DO NOT EDIT.

package ${packageName}

import (
\t"bytes"
\t"encoding/json"
\t"fmt"
\t"io"
\t"net/http"
\t"net/url"
\t"strconv"
\t"strings"
)

// Keep imports live even when a given spec does not exercise them.
var (
\t_ = strconv.Itoa
\t_ = strings.Replace
\t_ = bytes.NewReader
)

// Client is the HTTP client for the API.
type Client struct {
\tBaseURL    string
\tToken      string
\tHTTPClient *http.Client
}

// NewClient builds a Client with the default \`net/http\` client.
func NewClient(baseURL, token string) *Client {
\treturn &Client{
\t\tBaseURL:    trimSuffix(baseURL, "/"),
\t\tToken:      token,
\t\tHTTPClient: http.DefaultClient,
\t}
}

// FromSpec reads the JSON OpenAPI document at specURL and builds a client
// whose baseURL comes from the first \`servers[]\` entry.
func FromSpec(specURL, token string) (*Client, error) {
\tresp, err := http.Get(specURL)
\tif err != nil {
\t\treturn nil, fmt.Errorf("fetch spec: %w", err)
\t}
\tdefer resp.Body.Close()
\tif resp.StatusCode < 200 || resp.StatusCode >= 300 {
\t\treturn nil, fmt.Errorf("fetch spec: HTTP %d", resp.StatusCode)
\t}
\tvar spec struct {
\t\tServers []struct {
\t\t\tURL string \`json:"url"\`
\t\t} \`json:"servers"\`
\t}
\tif err := json.NewDecoder(resp.Body).Decode(&spec); err != nil {
\t\treturn nil, fmt.Errorf("decode spec: %w", err)
\t}
\tif len(spec.Servers) == 0 {
\t\treturn nil, fmt.Errorf("OpenAPI spec at %s has no servers[]", specURL)
\t}
\treturn NewClient(spec.Servers[0].URL, token), nil
}

// APIError is returned for non-2xx responses.
type APIError struct {
\tStatus int
\tBody   []byte
}

func (e *APIError) Error() string {
\treturn fmt.Sprintf("HTTP %d: %s", e.Status, string(e.Body))
}

func (c *Client) headers(extra map[string]string) http.Header {
\th := http.Header{}
\th.Set("Accept", "application/json")
\tif c.Token != "" {
\t\th.Set("Authorization", "Bearer "+c.Token)
\t}
\tfor k, v := range extra {
\t\th.Set(k, v)
\t}
\treturn h
}

func (c *Client) do(method, rawURL string, body any, extraHeaders map[string]string) (any, error) {
\tvar reader io.Reader
\theaders := c.headers(extraHeaders)
\tif body != nil {
\t\tbuf, err := json.Marshal(body)
\t\tif err != nil {
\t\t\treturn nil, fmt.Errorf("marshal body: %w", err)
\t\t}
\t\treader = bytes.NewReader(buf)
\t\theaders.Set("Content-Type", "application/json")
\t}
\treq, err := http.NewRequest(method, rawURL, reader)
\tif err != nil {
\t\treturn nil, err
\t}
\treq.Header = headers
\tresp, err := c.HTTPClient.Do(req)
\tif err != nil {
\t\treturn nil, err
\t}
\tdefer resp.Body.Close()
\trespBody, _ := io.ReadAll(resp.Body)
\tif resp.StatusCode < 200 || resp.StatusCode >= 300 {
\t\treturn nil, &APIError{Status: resp.StatusCode, Body: respBody}
\t}
\tif len(respBody) == 0 {
\t\treturn nil, nil
\t}
\tvar out any
\tif err := json.Unmarshal(respBody, &out); err != nil {
\t\treturn respBody, nil
\t}
\treturn out, nil
}

func trimSuffix(s, suffix string) string {
\tif len(s) >= len(suffix) && s[len(s)-len(suffix):] == suffix {
\t\treturn s[:len(s)-len(suffix)]
\t}
\treturn s
}

${methods}
`;
}

function renderMethod(op: NormalisedOperation): string {
  const name = goExportedIdentifier(op.operationId);
  const pathArgs: string[] = [];
  const pathSubstitutions: string[] = [];

  for (const p of op.pathParams) {
    const ident = sanitizeGoParam(p.name);
    const goType = goTypeForSchema(p.schema);
    pathArgs.push(`${ident} ${goType}`);
    pathSubstitutions.push(
      `\tpath = strings.Replace(path, "{${p.name}}", url.PathEscape(${goToString(ident, goType)}), 1)`,
    );
  }

  const queryFields: string[] = [];
  const queryAssignments: string[] = [];
  for (const p of op.queryParams) {
    const ident = sanitizeGoParam(p.name);
    const goType = goTypeForSchema(p.schema);
    if (p.required) {
      queryFields.push(`${ident} ${goType}`);
      queryAssignments.push(
        `\tq.Set(${JSON.stringify(p.name)}, ${goToString(ident, goType)})`,
      );
    } else {
      queryFields.push(`${ident} *${goType}`);
      queryAssignments.push(
        `\tif ${ident} != nil { q.Set(${JSON.stringify(p.name)}, ${goToString(`*${ident}`, goType)}) }`,
      );
    }
  }

  const args = [...pathArgs, ...queryFields];
  if (op.requestBodySchema) args.push("body any");
  args.push("extraHeaders map[string]string");

  const doc = `// ${name}${op.summary ? " — " + op.summary : ""}.\n// ${op.method.toUpperCase()} ${op.path}`;

  return `${doc}
func (c *Client) ${name}(${args.join(", ")}) (any, error) {
\tpath := ${JSON.stringify(op.path)}
${pathSubstitutions.join("\n")}
\tu, err := url.Parse(c.BaseURL + path)
\tif err != nil { return nil, err }
\tq := u.Query()
${queryAssignments.join("\n")}
\tu.RawQuery = q.Encode()
\treturn c.do(${JSON.stringify(op.method.toUpperCase())}, u.String(), ${op.requestBodySchema ? "body" : "nil"}, extraHeaders)
}`;
}

function goTypeForSchema(schema: unknown): string {
  if (!schema || typeof schema !== "object") return "any";
  const s = schema as Record<string, unknown>;
  if (Array.isArray(s.enum)) return "string";
  switch (s.type) {
    case "string":
      return "string";
    case "integer":
      return "int";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "array":
      return "[]any";
    case "object":
      return "any";
    default:
      return "any";
  }
}

function goToString(ident: string, goType: string): string {
  switch (goType) {
    case "string":
      return ident;
    case "int":
      return `strconv.Itoa(${ident})`;
    case "float64":
      return `strconv.FormatFloat(${ident}, 'f', -1, 64)`;
    case "bool":
      return `strconv.FormatBool(${ident})`;
    default:
      return `fmt.Sprintf("%v", ${ident})`;
  }
}

const GO_KEYWORDS = new Set([
  "break", "case", "chan", "const", "continue", "default", "defer", "else",
  "fallthrough", "for", "func", "go", "goto", "if", "import", "interface",
  "map", "package", "range", "return", "select", "struct", "switch", "type",
  "var",
]);

function sanitizeGoParam(raw: string): string {
  let id = raw.replace(/[^a-zA-Z0-9_]/g, "_");
  if (/^[0-9]/.test(id)) id = `_${id}`;
  if (GO_KEYWORDS.has(id)) id = `${id}_`;
  // Go param convention: camelCase lower first letter.
  return id[0]!.toLowerCase() + id.slice(1);
}
