import type { Oas } from "@mihari/oas";

import {
  camelCase,
  iterSchemas,
  kebabCase,
  listOperations,
  pascalCase,
  schemaIsArrayOfRef,
  schemaIsRef,
  schemaToPhp,
  specTitle,
  type GenerateResult,
  type NormalisedOperation,
} from "./shared.ts";

export interface GenerateSdkPhpOptions {
  /** Composer vendor (first half of the package name). Default: `example`. */
  vendor?: string;
  /** Composer package name (second half). Default: kebab-case title + `-sdk`. */
  packageName?: string;
  /** PHP class name. Default: derived from title. */
  className?: string;
  /** Emit methods that return `GuzzleHttp\Promise\PromiseInterface`. */
  async?: boolean;
}

/**
 * Generates a PHP 8.1+ SDK backed by Guzzle. Methods return `mixed` (the
 * decoded JSON response). Non-2xx responses bubble up as Guzzle exceptions
 * unless explicitly handled by the caller.
 */
export function generateSdkPhp(
  oas: Oas,
  options: GenerateSdkPhpOptions = {},
): GenerateResult {
  const title = specTitle(oas);
  const vendor = options.vendor ?? "example";
  const packageName = options.packageName ?? `${kebabCase(title)}-sdk`;
  const className = options.className ?? "Client";
  const namespace = `${pascalCase(vendor)}\\${pascalCase(title)}`;
  const operations = listOperations(oas);

  const schemas = iterSchemas(oas);
  const isAsync = options.async === true;

  return {
    files: [
      {
        path: "composer.json",
        content: renderComposerJson(vendor, packageName, namespace),
      },
      { path: ".gitignore", content: "/vendor/\ncomposer.lock\n" },
      {
        path: "README.md",
        content: renderReadme(title, vendor, packageName, namespace, className, isAsync),
      },
      {
        path: "src/ApiException.php",
        content: renderApiException(namespace),
      },
      ...schemas.map(({ name, schema }) => ({
        path: `src/${name}.php`,
        content: renderDto(namespace, name, schema),
      })),
      {
        path: `src/${className}.php`,
        content: renderClient(namespace, className, operations, isAsync),
      },
    ],
  };
}

function renderDto(namespace: string, name: string, schema: unknown): string {
  if (!schema || typeof schema !== "object") {
    return `<?php
declare(strict_types=1);

namespace ${namespace};

final class ${name} {}
`;
  }
  const s = schema as Record<string, unknown>;
  if (s.type !== "object" || !s.properties) {
    return `<?php
declare(strict_types=1);

namespace ${namespace};

// ${name} is not an object schema; extend this stub if you need typed access.
final class ${name} {}
`;
  }
  const properties = s.properties as Record<string, unknown>;
  const required = new Set(Array.isArray(s.required) ? (s.required as string[]) : []);

  const constructorParams: string[] = [];
  const fromArrayLines: string[] = [];
  for (const [key, propSchema] of Object.entries(properties)) {
    const fieldName = camelCase(key).replace(/[^a-zA-Z0-9_]/g, "");
    const phpType = schemaToPhp(propSchema);
    const isRequired = required.has(key);
    const typeHint = isRequired ? phpType : `?${phpType}`;
    const def = isRequired ? "" : " = null";
    constructorParams.push(`        public readonly ${typeHint} $${fieldName}${def},`);
    const rawAccess = `$data[${JSON.stringify(key)}] ?? null`;
    fromArrayLines.push(`            ${fieldName}: ${rawAccess},`);
  }

  return `<?php
declare(strict_types=1);

namespace ${namespace};

/** Auto-generated DTO. Do not edit by hand. */
final class ${name}
{
    public function __construct(
${constructorParams.join("\n")}
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
${fromArrayLines.join("\n")}
        );
    }
}
`;
}

function renderComposerJson(vendor: string, packageName: string, namespace: string): string {
  // PSR-4 keys use single backslashes that must be doubled in JSON encoding.
  const psr4Key = `${namespace.replace(/\\/g, "\\\\")}\\\\`;
  const raw = {
    name: `${vendor}/${packageName}`,
    description: "Generated PHP SDK",
    type: "library",
    require: {
      php: ">=8.1",
      "guzzlehttp/guzzle": "^7.0",
    },
    autoload: {
      "psr-4": {
        [psr4Key]: "src/",
      },
    },
    config: { "sort-packages": true },
  };
  return `${JSON.stringify(raw, null, 2)}\n`;
}

function renderReadme(
  title: string,
  vendor: string,
  packageName: string,
  namespace: string,
  className: string,
  isAsync: boolean,
): string {
  return `# ${title} SDK (PHP)

Generated by \`mihari api generate sdk --lang php\`. PHP 8.1+, built on
[Guzzle](https://docs.guzzlephp.org/). Methods return \`mixed\` (decoded JSON).

## Install

\`\`\`sh
composer install
\`\`\`

## Usage

\`\`\`php
use ${namespace}\\${className};

$client = new ${className}('https://api.example.com', 'token');
$pets = $client->listPets(limit: 10);
\`\`\`

Or resolve the base URL from the spec:

\`\`\`php
$client = ${className}::fromSpec('https://api.example.com/openapi.json', 'token');
\`\`\`

Composer package: \`${vendor}/${packageName}\`.
`;
}

function renderApiException(namespace: string): string {
  return `<?php
declare(strict_types=1);

namespace ${namespace};

use RuntimeException;

/** Thrown for non-2xx HTTP responses. */
final class ApiException extends RuntimeException
{
    public function __construct(
        public readonly int $status,
        public readonly string $body,
    ) {
        parent::__construct("HTTP {$status}: {$body}");
    }
}
`;
}

function renderClient(
  namespace: string,
  className: string,
  operations: NormalisedOperation[],
  isAsync: boolean,
): string {
  const methods = operations.map((op) => renderMethod(op, isAsync)).join("\n\n");
  return `<?php
declare(strict_types=1);

namespace ${namespace};

use GuzzleHttp\\Client as HttpClient;
use GuzzleHttp\\RequestOptions;

/** Auto-generated client. Do not edit by hand. */
final class ${className}
{
    private HttpClient $http;

    public function __construct(
        private readonly string $baseUrl,
        private readonly ?string $token = null,
        ?HttpClient $http = null,
    ) {
        $this->http = $http ?? new HttpClient();
    }

    /** Build a client by reading \`servers[0].url\` from the JSON spec at $specUrl. */
    public static function fromSpec(string $specUrl, ?string $token = null): self
    {
        $http = new HttpClient();
        $resp = $http->get($specUrl);
        if ($resp->getStatusCode() < 200 || $resp->getStatusCode() >= 300) {
            throw new ApiException($resp->getStatusCode(), (string) $resp->getBody());
        }
        $decoded = json_decode((string) $resp->getBody(), true);
        $url = $decoded['servers'][0]['url'] ?? null;
        if (!is_string($url)) {
            throw new \\RuntimeException("OpenAPI spec at {$specUrl} has no servers[]");
        }
        return new self($url, $token);
    }

    private function headers(array $extra = []): array
    {
        $h = ['Accept' => 'application/json'];
        if ($this->token !== null) {
            $h['Authorization'] = 'Bearer ' . $this->token;
        }
        return array_merge($h, $extra);
    }

    private function url(string $path): string
    {
        return rtrim($this->baseUrl, '/') . $path;
    }

${methods}
}
`;
}

function renderMethod(op: NormalisedOperation, isAsync: boolean): string {
  const name = camelCase(op.operationId);
  const pathArgs: string[] = [];
  const pathLines: string[] = [];

  for (const p of op.pathParams) {
    const ident = `$${camelCase(p.name)}`;
    const phpType = phpTypeForSchema(p.schema);
    pathArgs.push(`${phpType} ${ident}`);
    pathLines.push(
      `        $path = str_replace('{${p.name}}', rawurlencode((string) ${ident}), $path);`,
    );
  }

  const namedArgs: string[] = [];
  const queryLines: string[] = [];
  for (const p of op.queryParams) {
    const ident = `$${camelCase(p.name)}`;
    const phpType = phpTypeForSchema(p.schema);
    const nullable = p.required ? "" : "?";
    const defaultExpr = p.required ? "" : " = null";
    namedArgs.push(`${nullable}${phpType} ${ident}${defaultExpr}`);
    if (p.required) {
      queryLines.push(`        $query[${JSON.stringify(p.name)}] = ${ident};`);
    } else {
      queryLines.push(`        if (${ident} !== null) $query[${JSON.stringify(p.name)}] = ${ident};`);
    }
  }

  const hasBody = !!op.requestBodySchema;
  if (hasBody) {
    const bodyType = phpBodyType(op);
    if (op.requestBodyRequired) {
      namedArgs.push(`${bodyType} $body`);
    } else {
      namedArgs.push(`?${bodyType} $body = null`);
    }
  }

  const allArgs = [...pathArgs, ...namedArgs];
  const method = op.method.toUpperCase();
  const { returnType, returnExpr } = phpReturn(op);

  const doc = op.summary
    ? `    /** ${op.summary} — ${method} ${op.path} */`
    : `    /** ${method} ${op.path} */`;

  const queryBlock = op.queryParams.length
    ? `        $query = [];\n${queryLines.join("\n")}`
    : "        $query = [];";

  const requestOptions: string[] = [
    "            RequestOptions::HEADERS => $this->headers()",
    "            RequestOptions::HTTP_ERRORS => false",
    "            RequestOptions::QUERY => $query",
  ];
  if (hasBody) {
    requestOptions.push("            RequestOptions::JSON => $body");
  }

  const pathReplacement = pathLines.length
    ? pathLines.join("\n")
    : "        // no path params";

  if (isAsync) {
    return `${doc}
    public function ${name}(${allArgs.join(", ")}): \\GuzzleHttp\\Promise\\PromiseInterface
    {
        $path = ${JSON.stringify(op.path)};
${pathReplacement}
${queryBlock}
        return $this->http->requestAsync(
            ${JSON.stringify(method)},
            $this->url($path),
            [
${requestOptions.join(",\n")},
            ],
        )->then(function ($response) {
            $status = $response->getStatusCode();
            $body = (string) $response->getBody();
            if ($status < 200 || $status >= 300) {
                throw new ApiException($status, $body);
            }
            if ($body === '') return null;
            $ct = $response->getHeaderLine('content-type');
            if (!str_contains($ct, 'application/json')) {
                return $body;
            }
            $decoded = json_decode($body, true);
            return ${returnExpr};
        });
    }`;
  }

  return `${doc}
    public function ${name}(${allArgs.join(", ")}): ${returnType}
    {
        $path = ${JSON.stringify(op.path)};
${pathReplacement}
${queryBlock}
        $response = $this->http->request(
            ${JSON.stringify(method)},
            $this->url($path),
            [
${requestOptions.join(",\n")},
            ],
        );
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if ($status < 200 || $status >= 300) {
            throw new ApiException($status, $body);
        }
        if ($body === '') return null;
        $ct = $response->getHeaderLine('content-type');
        if (!str_contains($ct, 'application/json')) {
            return $body;
        }
        $decoded = json_decode($body, true);
        return ${returnExpr};
    }`;
}

function phpReturn(op: NormalisedOperation): { returnType: string; returnExpr: string } {
  const schema = op.successResponse?.schema;
  if (!schema) return { returnType: "mixed", returnExpr: "$decoded" };
  const refName = schemaIsRef(schema);
  if (refName) {
    return {
      returnType: `?${refName}`,
      returnExpr: `is_array($decoded) ? ${refName}::fromArray($decoded) : null`,
    };
  }
  const arrayRef = schemaIsArrayOfRef(schema);
  if (arrayRef) {
    return {
      returnType: "array",
      returnExpr: `array_map(fn($row) => ${arrayRef}::fromArray($row), (array) $decoded)`,
    };
  }
  return { returnType: "mixed", returnExpr: "$decoded" };
}

function phpBodyType(op: NormalisedOperation): string {
  const schema = op.requestBodySchema;
  if (!schema) return "mixed";
  const refName = schemaIsRef(schema);
  if (refName) return refName;
  const arrayRef = schemaIsArrayOfRef(schema);
  if (arrayRef) return "array";
  return "mixed";
}

function phpTypeForSchema(schema: unknown): string {
  if (!schema || typeof schema !== "object") return "mixed";
  const s = schema as Record<string, unknown>;
  if (Array.isArray(s.enum)) return "string";
  switch (s.type) {
    case "string":
      return "string";
    case "integer":
      return "int";
    case "number":
      return "float";
    case "boolean":
      return "bool";
    case "array":
      return "array";
    case "object":
      return "array";
    default:
      return "mixed";
  }
}
