import type { Oas } from "@mihari/oas";

import {
  clientClassNameFromTitle,
  honoClientPathTemplate,
  iterSchemas,
  kebabCase,
  listOperations,
  schemaToTs,
  specTitle,
  type GenerateResult,
  type NormalisedOperation,
} from "./shared.ts";

export interface GenerateSdkOptions {
  packageName?: string;
  className?: string;
}

export function generateSdk(oas: Oas, options: GenerateSdkOptions = {}): GenerateResult {
  const title = specTitle(oas);
  const packageName = options.packageName ?? `${kebabCase(title)}-sdk`;
  const className = options.className ?? clientClassNameFromTitle(title);
  const operations = listOperations(oas);
  const schemas = iterSchemas(oas);

  return {
    files: [
      { path: "package.json", content: renderPackageJson(packageName) },
      { path: "tsconfig.json", content: renderTsconfig() },
      { path: "tsconfig.build.json", content: renderTsconfigBuild() },
      { path: ".npmignore", content: renderNpmIgnore() },
      { path: "README.md", content: renderReadme(title, className) },
      { path: "src/types.ts", content: renderTypes(schemas) },
      { path: "src/client.ts", content: renderClient(className, operations) },
      {
        path: "src/index.ts",
        content: `export * from "./client.js";\nexport * from "./types.js";\n`,
      },
    ],
  };
}

function renderPackageJson(name: string): string {
  return (
    JSON.stringify(
      {
        name,
        version: "0.1.0",
        type: "module",
        main: "./dist/index.cjs",
        module: "./dist/index.js",
        types: "./dist/index.d.ts",
        exports: {
          ".": {
            types: "./dist/index.d.ts",
            import: "./dist/index.js",
            require: "./dist/index.cjs",
          },
        },
        files: ["dist", "README.md"],
        scripts: {
          build: "bun run clean && bun run build:esm && bun run build:cjs && bun run build:types",
          "build:esm":
            "bun build src/index.ts --outfile dist/index.js --format esm --target node",
          "build:cjs":
            "bun build src/index.ts --outfile dist/index.cjs --format cjs --target node",
          "build:types": "tsc -p tsconfig.build.json",
          clean: "rm -rf dist",
          typecheck: "tsc --noEmit",
          prepublishOnly: "bun run build",
        },
        devDependencies: {
          "@types/bun": "latest",
          typescript: "^5.7.0",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function renderNpmIgnore(): string {
  return ["src", "tsconfig.json", "tsconfig.build.json", ".npmignore", ""].join("\n");
}

function renderTsconfigBuild(): string {
  return (
    JSON.stringify(
      {
        extends: "./tsconfig.json",
        compilerOptions: {
          noEmit: false,
          declaration: true,
          declarationMap: true,
          emitDeclarationOnly: true,
          outDir: "dist",
          rootDir: "src",
          // Source uses `.js` specifiers that resolve to `.ts` via bundler
          // resolution at build time, so we don't need the .ts-in-imports hack.
          allowImportingTsExtensions: false,
          verbatimModuleSyntax: false,
        },
        include: ["src"],
      },
      null,
      2,
    ) + "\n"
  );
}

function renderTsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ESNext",
          module: "ESNext",
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          noEmit: true,
          strict: true,
          skipLibCheck: true,
          esModuleInterop: true,
          isolatedModules: true,
          verbatimModuleSyntax: true,
          types: ["bun-types"],
          lib: ["ESNext"],
        },
        include: ["src"],
      },
      null,
      2,
    ) + "\n"
  );
}

function renderReadme(title: string, className: string): string {
  return `# ${title} SDK

Generated by \`mihari api generate sdk\`. One typed method per operation in the OpenAPI spec.

## Usage

\`\`\`ts
import { ${className} } from "${kebabCase(title)}-sdk";

const client = new ${className}({
  baseUrl: "https://api.example.com",
  token: process.env.API_TOKEN,
});

// ...or let the client discover baseUrl from the spec's servers[]:
const clientFromSpec = await ${className}.fromSpec("https://api.example.com/openapi.json", {
  token: process.env.API_TOKEN,
});
\`\`\`

Methods are generated from \`operationId\`. Path/query/header inputs live on \`input.path\`, \`input.query\` and \`input.headers\`; bodies land on \`input.body\`. Unrecognised schema shapes fall back to \`unknown\` — edit \`src/types.ts\` to tighten them.

## Build & publish

\`\`\`sh
bun install
bun run build       # emits dist/index.js (ESM), dist/index.cjs, dist/index.d.ts
npm publish         # \`prepublishOnly\` re-runs the build
\`\`\`

The package exposes dual entry points via the \`exports\` field (\`import\` → ESM, \`require\` → CJS) and ships TypeScript declarations.
`;
}

function renderTypes(schemas: Array<{ name: string; schema: unknown }>): string {
  if (!schemas.length) return "// No components.schemas defined in the spec.\nexport {};\n";
  return schemas
    .map(({ name, schema }) => {
      const body = schemaToTs(schema);
      if (body.startsWith("{\n")) {
        return `export interface ${name} ${body}`;
      }
      return `export type ${name} = ${body};`;
    })
    .join("\n\n") + "\n";
}

function renderClient(className: string, operations: NormalisedOperation[]): string {
  const methods = operations.map((op) => renderMethod(op)).join("\n\n");
  return `import type * as Schemas from "./types.js";

export interface ClientOptions {
  baseUrl: string;
  token?: string;
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
}

export class ${className} {
  constructor(private readonly options: ClientOptions) {}

  /**
   * Builds a client by fetching an OpenAPI document and picking its first
   * server URL as baseUrl. The spec must be JSON — parse YAML yourself and
   * pass \`baseUrl\` explicitly if your spec is YAML.
   */
  static async fromSpec(
    specUrl: string,
    options: Omit<ClientOptions, "baseUrl"> = {},
  ): Promise<${className}> {
    const fetcher = options.fetch ?? fetch;
    const response = await fetcher(specUrl);
    if (!response.ok) {
      throw new Error(\`Failed to fetch OpenAPI spec \${specUrl}: HTTP \${response.status}\`);
    }
    const text = await response.text();
    let spec: { servers?: Array<{ url: string }> };
    try {
      spec = JSON.parse(text);
    } catch (error) {
      throw new Error(
        \`OpenAPI spec at \${specUrl} must be JSON. Parse YAML yourself and construct the client with an explicit baseUrl. (\${(error as Error).message})\`,
      );
    }
    const baseUrl = spec.servers?.[0]?.url;
    if (!baseUrl) {
      throw new Error(\`OpenAPI spec at \${specUrl} has no servers[] — cannot determine baseUrl\`);
    }
    return new ${className}({ baseUrl, ...options });
  }

${methods}

  private buildHeaders(extra?: Record<string, string>): Record<string, string> {
    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.options.defaultHeaders) Object.assign(headers, this.options.defaultHeaders);
    if (this.options.token) headers.Authorization = \`Bearer \${this.options.token}\`;
    if (extra) Object.assign(headers, extra);
    return headers;
  }

  private async request(
    method: string,
    path: string,
    init: { query?: Record<string, string | number | boolean | undefined>; headers?: Record<string, string>; body?: unknown } = {},
  ): Promise<Response> {
    const url = new URL(path, this.options.baseUrl);
    if (init.query) {
      for (const [key, value] of Object.entries(init.query)) {
        if (value !== undefined) url.searchParams.set(key, String(value));
      }
    }
    const headers = this.buildHeaders(init.headers);
    let body: string | undefined;
    if (init.body !== undefined) {
      body = typeof init.body === "string" ? init.body : JSON.stringify(init.body);
      headers["Content-Type"] ??= "application/json";
    }
    const fetcher = this.options.fetch ?? fetch;
    const response = await fetcher(url.toString(), {
      method,
      headers,
      ...(body !== undefined ? { body } : {}),
    });
    if (!response.ok) {
      throw new Error(\`\${method} \${path} -> HTTP \${response.status}\`);
    }
    return response;
  }
}
`;
}

function renderMethod(op: NormalisedOperation): string {
  const inputType = renderInputType(op);
  const responseType = op.successResponse?.schema ? schemaToTs(op.successResponse.schema, { refNamespace: "Schemas" }) : "unknown";
  const inputOptional = inputType === "void" ? "?" : "";
  const inputArg = inputType === "void" ? `input?: undefined` : `input: ${inputType}`;
  const template = `\`${honoClientPathTemplate(op.path)}\``;
  const queryLine = op.queryParams.length
    ? `      query: input${inputOptional}.query as Record<string, string | number | boolean | undefined> | undefined,`
    : "";
  const headersLine = op.headerParams.length
    ? `      headers: input${inputOptional}.headers as Record<string, string> | undefined,`
    : "";
  const bodyLine = op.requestBodySchema
    ? `      body: input${inputOptional}.body,`
    : "";

  const initLines = [queryLine, headersLine, bodyLine].filter(Boolean).join("\n");
  const initBlock = initLines ? `, {\n${initLines}\n    }` : "";
  const summaryDoc = op.summary ? `  /** ${op.summary} */\n` : "";
  const sig = inputType === "void"
    ? `async ${op.safeId}(): Promise<${responseType}>`
    : `async ${op.safeId}(${inputArg}): Promise<${responseType}>`;

  return `${summaryDoc}  ${sig} {
    const response = await this.request(${JSON.stringify(op.method.toUpperCase())}, ${template}${initBlock});
    return response.json() as Promise<${responseType}>;
  }`;
}

function renderInputType(op: NormalisedOperation): string {
  const sections: string[] = [];
  if (op.pathParams.length) {
    const body = op.pathParams
      .map((p) => `    ${safeKey(p.name)}: ${schemaToTs(p.schema, { refNamespace: "Schemas" })};`)
      .join("\n");
    sections.push(`  path: {\n${body}\n  };`);
  }
  if (op.queryParams.length) {
    const body = op.queryParams
      .map((p) => `    ${safeKey(p.name)}${p.required ? "" : "?"}: ${schemaToTs(p.schema, { refNamespace: "Schemas" })};`)
      .join("\n");
    sections.push(`  query${op.queryParams.some((p) => p.required) ? "" : "?"}: {\n${body}\n  };`);
  }
  if (op.headerParams.length) {
    sections.push(`  headers?: Record<string, string>;`);
  }
  if (op.requestBodySchema) {
    const bodyType = schemaToTs(op.requestBodySchema, { refNamespace: "Schemas" });
    const required = op.requestBodyRequired ? "" : "?";
    sections.push(`  body${required}: ${bodyType};`);
  }
  if (!sections.length) return "void";
  return `{\n${sections.join("\n")}\n}`;
}

function safeKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
